// Emits TypeScript bindings for every serdeable type in this crate to
// `frontend/src/api/types.gen.ts`. ts-rs derives live on the Rust types
// themselves; this script writes the consolidated TS file deterministically
// off the current type set. CI's `git diff --exit-code` on the generated
// file catches drift between the Rust schema and the committed bindings.
//
// As later phases add types to nyx-agent-types, append the matching TS
// declarations here. Output stays sorted/grouped so diffs remain stable.

use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/event.rs");
    println!("cargo:rerun-if-changed=src/finding.rs");
    println!("cargo:rerun-if-changed=src/repo.rs");
    println!("cargo:rerun-if-changed=src/run.rs");
    println!("cargo:rerun-if-changed=src/payload.rs");
    println!("cargo:rerun-if-changed=src/chain.rs");
    println!("cargo:rerun-if-changed=src/verify.rs");
    println!("cargo:rerun-if-changed=src/agent.rs");
    println!("cargo:rerun-if-changed=src/budget.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out_path = manifest_dir
        .join("..")
        .join("..")
        .join("frontend")
        .join("src")
        .join("api")
        .join("types.gen.ts");

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).expect("create frontend types output dir");
    }

    let content = render();

    let prior = fs::read_to_string(&out_path).unwrap_or_default();
    if prior != content {
        fs::write(&out_path, content).expect("write types.gen.ts");
    }
}

fn render() -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED FILE. DO NOT EDIT.\n");
    out.push_str("// Regenerated by crates/nyx-agent-types/build.rs on `cargo build`.\n");
    out.push_str("// Source of truth: Rust types in crates/nyx-agent-types/src/.\n");
    out.push('\n');
    out.push_str("export type RepoOutcomeTag = \"Success\" | \"Inconclusive\" | \"Failed\";\n");
    out.push('\n');
    out.push_str("export type RunEvent =\n");
    out.push_str("  | { kind: \"Heartbeat\"; ts: number }\n");
    out.push_str(
        "  | { kind: \"RunStarted\"; run_id: string; repos: string[]; \
         started_at_ms: number }\n",
    );
    out.push_str(
        "  | { kind: \"RepoStarted\"; run_id: string; repo: string; \
         started_at_ms: number }\n",
    );
    out.push_str(
        "  | { kind: \"RepoStaticDone\"; run_id: string; repo: string; \
         n_diags: number; elapsed_ms: number }\n",
    );
    out.push_str(
        "  | { kind: \"RepoDynamicDone\"; run_id: string; repo: string; \
         elapsed_ms: number }\n",
    );
    out.push_str(
        "  | { kind: \"RepoFailed\"; run_id: string; repo: string; \
         message: string; elapsed_ms: number }\n",
    );
    out.push_str(
        "  | { kind: \"RepoFinished\"; run_id: string; repo: string; \
         outcome: RepoOutcomeTag; elapsed_ms: number }\n",
    );
    out.push_str(
        "  | { kind: \"RunFinished\"; run_id: string; finished_at_ms: number; \
         wall_clock_ms: number; succeeded: number; inconclusive: number; \
         failed: number };\n",
    );
    out.push('\n');
    out.push_str("export type AiEvent = Record<string, never>;\n");
    out.push_str("export type SandboxEvent = Record<string, never>;\n");
    out.push_str("export type FindingEvent = Record<string, never>;\n");
    out.push_str("export type BudgetEvent = Record<string, never>;\n");
    out.push_str("export type QuarantineEvent = Record<string, never>;\n");
    out.push_str("export type ReproEvent = Record<string, never>;\n");
    out.push('\n');
    out.push_str("export type AgentEvent =\n");
    out.push_str("  | { kind: \"Run\"; data: RunEvent }\n");
    out.push_str("  | { kind: \"Ai\"; data: AiEvent }\n");
    out.push_str("  | { kind: \"Sandbox\"; data: SandboxEvent }\n");
    out.push_str("  | { kind: \"Finding\"; data: FindingEvent }\n");
    out.push_str("  | { kind: \"Budget\"; data: BudgetEvent }\n");
    out.push_str("  | { kind: \"Quarantine\"; data: QuarantineEvent }\n");
    out.push_str("  | { kind: \"Repro\"; data: ReproEvent };\n");
    out
}
