// AUTO-GENERATED FILE. DO NOT EDIT.
// Regenerated by crates/nyx-agent-types/build.rs on `cargo build`.
// Source of truth: Rust types in crates/nyx-agent-types/src/.

export type RunEvent =
  | { kind: "Heartbeat"; ts: number };

export type AiEvent = Record<string, never>;
export type SandboxEvent = Record<string, never>;
export type FindingEvent = Record<string, never>;
export type BudgetEvent = Record<string, never>;
export type QuarantineEvent = Record<string, never>;
export type ReproEvent = Record<string, never>;

export type AgentEvent =
  | { kind: "Run"; data: RunEvent }
  | { kind: "Ai"; data: AiEvent }
  | { kind: "Sandbox"; data: SandboxEvent }
  | { kind: "Finding"; data: FindingEvent }
  | { kind: "Budget"; data: BudgetEvent }
  | { kind: "Quarantine"; data: QuarantineEvent }
  | { kind: "Repro"; data: ReproEvent };
