// AUTO-GENERATED FILE. DO NOT EDIT.
// Regenerated by crates/nyx-agent-types/build.rs on `cargo build`.
// Source of truth: Rust types in crates/nyx-agent-types/src/.

export type RepoOutcomeTag = "Success" | "Inconclusive" | "Failed";

export type RunEvent =
  | { kind: "Heartbeat"; ts: number }
  | { kind: "RunStarted"; run_id: string; repos: string[]; started_at_ms: number }
  | { kind: "RepoStarted"; run_id: string; repo: string; started_at_ms: number }
  | { kind: "RepoStaticDone"; run_id: string; repo: string; n_diags: number; elapsed_ms: number }
  | { kind: "RepoDynamicDone"; run_id: string; repo: string; elapsed_ms: number }
  | { kind: "RepoFailed"; run_id: string; repo: string; message: string; elapsed_ms: number }
  | { kind: "RepoFinished"; run_id: string; repo: string; outcome: RepoOutcomeTag; elapsed_ms: number }
  | { kind: "RunFinished"; run_id: string; finished_at_ms: number; wall_clock_ms: number; succeeded: number; inconclusive: number; failed: number };

export type AiEvent = Record<string, never>;
export type SandboxEvent = Record<string, never>;
export type FindingEvent = Record<string, never>;
export type BudgetEvent = Record<string, never>;
export type QuarantineEvent = Record<string, never>;
export type ReproEvent = Record<string, never>;

export type AgentEvent =
  | { kind: "Run"; data: RunEvent }
  | { kind: "Ai"; data: AiEvent }
  | { kind: "Sandbox"; data: SandboxEvent }
  | { kind: "Finding"; data: FindingEvent }
  | { kind: "Budget"; data: BudgetEvent }
  | { kind: "Quarantine"; data: QuarantineEvent }
  | { kind: "Repro"; data: ReproEvent };
