// AUTO-GENERATED FILE. DO NOT EDIT.
// Regenerated by crates/nyx-agent-types/build.rs on `cargo build`.
// Source of truth: Rust types in crates/nyx-agent-types/src/.

export type RepoOutcomeTag = "Success" | "Inconclusive" | "Failed";

export type RunEvent =
  | { kind: "Heartbeat"; ts: number }
  | { kind: "RunStarted"; run_id: string; repos: string[]; started_at_ms: number }
  | { kind: "RepoStarted"; run_id: string; repo: string; started_at_ms: number }
  | { kind: "RepoStaticDone"; run_id: string; repo: string; n_diags: number; elapsed_ms: number }
  | { kind: "RepoDynamicDone"; run_id: string; repo: string; elapsed_ms: number }
  | { kind: "RepoFailed"; run_id: string; repo: string; message: string; elapsed_ms: number }
  | { kind: "RepoFinished"; run_id: string; repo: string; outcome: RepoOutcomeTag; elapsed_ms: number }
  | { kind: "RunFinished"; run_id: string; finished_at_ms: number; wall_clock_ms: number; succeeded: number; inconclusive: number; failed: number };

export type HaltReason =
  | "BudgetCapReached"
  | "OperatorCancelled"
  | "UpstreamRefused";

export type AiEvent =
  | { kind: "TokenReceived"; task_id: string; token: string }
  | { kind: "ToolCallStarted"; task_id: string; name: string }
  | { kind: "ToolCallFinished"; task_id: string; name: string; ok: boolean }
  | { kind: "CacheHit"; task_id: string; tokens: number }
  | { kind: "CacheMiss"; task_id: string; tokens: number }
  | { kind: "BudgetTick"; task_id: string; run_id: string; spent_usd_micros: number }
  | { kind: "TaskHalted"; task_id: string; reason: HaltReason };

export type BudgetKind = "OneShot" | "AgentLoop" | "Total";

export interface TokenUsage {
  input_tokens: number;
  output_tokens: number;
}

export interface CacheStats {
  cache_creation_tokens: number;
  cache_read_tokens: number;
}

export interface Budget {
  run_id: string;
  kind: BudgetKind;
  cap_usd_micros: number;
}

export interface CostEstimate {
  min_usd_micros: number;
  max_usd_micros: number;
}

export interface Prompt {
  prompt_version: string;
  task_id: string;
  model: string | null;
  system: string;
  user: string;
  max_output_tokens: number;
  temperature: number;
  seed: number | null;
}

export interface Response {
  prompt_version: string;
  task_id: string;
  model: string;
  content: string;
  usage: TokenUsage;
  cache: CacheStats | null;
  cost_usd_micros: number;
}

export interface AgentTask {
  prompt_version: string;
  task_id: string;
  system: string;
  objective: string;
  tools: string[];
  max_turns: number;
}

export type ExtractedAgentResult =
  | { kind: "PayloadFound"; rule_id: string; body: string }
  | { kind: "SpecFound"; capability: string; spec: string }
  | { kind: "ChainsRanked"; chain_ids: string[]; rationale: string }
  | { kind: "ExplorationFinding"; path: string; line: number | null; cap: string; rationale: string; endpoint: string | null; suggested_payload_hint: string | null }
  | { kind: "ExplorationEvent"; message: string };

export interface AgentResult {
  prompt_version: string;
  task_id: string;
  final_message: string;
  turns: number;
  usage: TokenUsage;
  cost_usd_micros: number;
  extracted: ExtractedAgentResult[];
}

export type SandboxEvent = Record<string, never>;
export type FindingEvent = Record<string, never>;
export type BudgetEvent = Record<string, never>;
export type QuarantineEvent = Record<string, never>;
export type ReproEvent = Record<string, never>;

export type AgentEvent =
  | { kind: "Run"; data: RunEvent }
  | { kind: "Ai"; data: AiEvent }
  | { kind: "Sandbox"; data: SandboxEvent }
  | { kind: "Finding"; data: FindingEvent }
  | { kind: "Budget"; data: BudgetEvent }
  | { kind: "Quarantine"; data: QuarantineEvent }
  | { kind: "Repro"; data: ReproEvent };
