-- v3 schema: agent_traces.verifier_blob column.
--
-- Phase 19 lands a Verifier task_kind row per deterministic
-- payload-runner call, but the row only carries duration + prompt
-- version. The trace viewer must join `findings` -> `verdict_blob` to
-- surface the spec id, the vuln/benign payload byte hashes, and the
-- per-run exit codes. Inlining a small JSON blob avoids the join.
--
-- Shape (when populated, all fields optional):
--   {
--     "spec_id": "spec-...",
--     "vuln_payload_sha256": "<hex>",
--     "vuln_exit_code": <int>,
--     "benign_payload_sha256": "<hex>",
--     "benign_exit_code": <int>
--   }
--
-- Verifier rows written before this migration carry NULL; the trace
-- viewer treats NULL as "fall back to the verdict_blob join".

ALTER TABLE agent_traces ADD COLUMN verifier_blob TEXT;
