// xtask binary. One subcommand today: `gen-ts` regenerates the
// frontend TypeScript bindings driven by the `#[derive(TS)]` annotations
// on every type in `nyx-agent-types`. CI invokes this binary and then
// runs `git diff --exit-code frontend/src/api/types.gen.ts` to catch
// drift between the Rust schema and the committed bindings.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

use nyx_agent_types::{
    agent::{
        AgentResult, AgentTask, Budget, BudgetKind, CacheStats, CostEstimate, ExtractedAgentResult,
        HaltReason, Prompt, Response, TokenUsage,
    },
    event::{
        AgentEvent, AiEvent, BudgetEvent, FindingEvent, QuarantineEvent, RepoOutcomeTag,
        ReproEvent, RunEvent, SandboxEvent,
    },
};
use ts_rs::TS;

fn main() -> ExitCode {
    let mut args = env::args().skip(1);
    let cmd = args.next();
    match cmd.as_deref() {
        Some("gen-ts") => match gen_ts() {
            Ok(()) => ExitCode::SUCCESS,
            Err(err) => {
                eprintln!("xtask gen-ts failed: {err}");
                ExitCode::from(1)
            }
        },
        Some(other) => {
            eprintln!("xtask: unknown subcommand `{other}` (try `gen-ts`)");
            ExitCode::from(2)
        }
        None => {
            eprintln!("xtask: missing subcommand (try `gen-ts`)");
            ExitCode::from(2)
        }
    }
}

fn gen_ts() -> Result<(), String> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .ok_or_else(|| "xtask Cargo.toml is not in a workspace".to_string())?;
    let out_path = workspace_root
        .join("frontend")
        .join("src")
        .join("api")
        .join("types.gen.ts");

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("create {}: {e}", parent.display()))?;
    }

    let body = render();
    fs::write(&out_path, body).map_err(|e| format!("write {}: {e}", out_path.display()))?;
    Ok(())
}

fn render() -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED FILE. DO NOT EDIT.\n");
    out.push_str("// Regenerated by `cargo run -p xtask -- gen-ts`.\n");
    out.push_str("// Source of truth: #[derive(TS)] types in crates/nyx-agent-types/src/.\n");
    out.push('\n');

    // Top-level types in dependency-friendly order. ts-rs `decl()`
    // produces a self-contained declaration per type; cross-type
    // references resolve at the TS level by name, so the order only
    // affects the file's readability, not correctness.
    let decls: Vec<String> = vec![
        decl_of::<RepoOutcomeTag>(),
        decl_of::<RunEvent>(),
        decl_of::<HaltReason>(),
        decl_of::<AiEvent>(),
        decl_of::<BudgetKind>(),
        decl_of::<TokenUsage>(),
        decl_of::<CacheStats>(),
        decl_of::<Budget>(),
        decl_of::<CostEstimate>(),
        decl_of::<Prompt>(),
        decl_of::<Response>(),
        decl_of::<AgentTask>(),
        decl_of::<ExtractedAgentResult>(),
        decl_of::<AgentResult>(),
        decl_of::<SandboxEvent>(),
        decl_of::<FindingEvent>(),
        decl_of::<BudgetEvent>(),
        decl_of::<QuarantineEvent>(),
        decl_of::<ReproEvent>(),
        decl_of::<AgentEvent>(),
    ];

    for decl in decls {
        out.push_str("export ");
        out.push_str(&decl);
        if !decl.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out
}

fn decl_of<T: TS>() -> String {
    <T as TS>::decl()
}
